//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdanBackup {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class configuracoes : global::System.Configuration.ApplicationSettingsBase {
        
        private static configuracoes defaultInstance = ((configuracoes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new configuracoes())));
        
        public static configuracoes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string destino {
            get {
                return ((string)(this["destino"]));
            }
            set {
                this["destino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string serverdrive {
            get {
                return ((string)(this["serverdrive"]));
            }
            set {
                this["serverdrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Lsthorabackup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Lsthorabackup"]));
            }
            set {
                this["Lsthorabackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GoogleAuth {
            get {
                return ((bool)(this["GoogleAuth"]));
            }
            set {
                this["GoogleAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProdanBackup.Odbc dadosOdbc {
            get {
                return ((global::ProdanBackup.Odbc)(this["dadosOdbc"]));
            }
            set {
                this["dadosOdbc"] = value;
            }
        }
    }
}
